version: 2
jobs:
  build:
    environment:
      JOBS: 1 # Disable parallelism to avoid errors to due to memory limits

    docker:
      - image: circleci/node:10

    working_directory: ~/baseapp

    steps:
      - checkout

      - run: sudo npm -g install yarn

      - run: yarn

      - run: yarn build

      - run: yarn lint

      - run: yarn test-ci

  bump_version:

    docker:
    - image: circleci/node:10

    working_directory: ~/baseapp

    steps:
      - checkout
      - run: sudo npm -g install yarn
      - run: git remote rm origin
      - run: git remote add origin https://gfedorenko:$GITHUB_TOKEN@github.com/openware/cryptobase.git
      - run: git config --global user.email "gfedorenko@heliostech.fr"
      - run: git config --global user.name "Galya Fedorenko"
      - run: lerna version patch --yes -m "NOJIRA Release new version and publish"
      - run: git push origin HEAD:develop

workflows:
  version: 2
  build_package:
    jobs:
      - build
      - bump_version:
          requires:
          - build
          filters:
            branches:
              only: /^\W*((?i)release(?-i))\W*$/
      - publish:
          requires:
          - build
          filters:
            branches:
              only: master
